CREATE TABLE `messaging` (
`GUID` BIGINT NOT NULL ,
`SENDER_NAME` VARCHAR( 64 ) ,
`RECIPIENT_NAME` VARCHAR( 64 ) ,
`SENDER_GUID` BIGINT,
`RECIPIENT_GUID` BIGINT,
`SUBJECT` VARCHAR( 255 ) ,
`BODY` TEXT,
`CREATED` BIGINT,
`VIEWED` TINYINT DEFAULT '0' NOT NULL ,
`PRIORITY` TINYINT DEFAULT '1' NOT NULL ,
PRIMARY KEY ( `GUID` ) 
);