CREATE TABLE `categories_info` (
`CATEGORY_ID` BIGINT NOT NULL ,
`VARIATION_ID` BIGINT NOT NULL ,
`IMAGE` BIGINT NOT NULL ,
`HEADER` TEXT NOT NULL ,
`FOOTER` TEXT NOT NULL ,
`TITLE` VARCHAR( 1024 ) NOT NULL ,
`SORT_ORDER` TINYINT NOT NULL ,
`DATE_ADDED` DATETIME NOT NULL ,
PRIMARY KEY ( `CATEGORY_ID` , `VARIATION_ID` ) 
) TYPE = MYISAM ;