CREATE TABLE `categories_info` (
`CATEGORY_ID` BIGINT NOT NULL ,
`TITLE` BIGINT NOT NULL ,
`IMAGE` BIGINT NOT NULL ,
`HEADER` BIGINT NOT NULL ,
`FOOTER` BIGINT NOT NULL ,
`SORT_ORDER` TINYINT NOT NULL ,
`DATE_ADDED` DATETIME NOT NULL ,
PRIMARY KEY ( `CATEGORY_ID` ) 
) TYPE = MYISAM ;