INSERT INTO `sys_functions` ( `FUNCTION_ID` , `PARENT_ID` , `NAME` , `DESCRIPTION` ) 
VALUES (
'ED_FOLDER_ACL', 'ED_FOLDER_PROPS', 'Set Access', 'Set Access to a folder an all object who reside within.'
);


CREATE TABLE `acl_relations` (
`GUID` BIGINT NOT NULL ,
`ACCESSOR_GUID` BIGINT NOT NULL ,
`ROLE_ID` BIGINT NOT NULL ,
INDEX ( `ACCESSOR_GUID` ) 
);


CREATE TABLE `acl_management` (
`GUID` BIGINT NOT NULL ,
`TYPE_ID` BIGINT,
`SYSTEM` TINYINT DEFAULT '0' NOT NULL ,
`INTERNAL` TINYINT DEFAULT '0' NOT NULL ,
`DISABLED` TINYINT DEFAULT '0' NOT NULL ,
`INHERIT` TINYINT DEFAULT '1' NOT NULL ,
`OWNER_GUID` BIGINT NOT NULL ,
`LOCKED_BY` BIGINT,
`LOCKED_AT` DATETIME,
PRIMARY KEY ( `GUID` ) 
);